APRENDENDO A UTILIZAR A BIBLIOTECA NUMPY

--> Principais Características do NumPy:
    Arrays N-dimensionais: Suporte para arrays de qualquer dimensão, permitindo operações complexas de forma simples e eficiente.
    Funções Matemáticas: Inclui funções para álgebra linear, transformadas de Fourier, geração de números aleatórios, entre outras.
    Desempenho: O núcleo do NumPy é escrito em C, proporcionando alta performance.
    Interoperabilidade: Funciona bem com outras bibliotecas de computação científica e de dados, como SciPy, Pandas, e Matplotlib

In [1]:
import numpy as np
#importando a biblioteca numpy


In [2]:
# array tradicional python
arr = [0, 2, 3, 5]
print(arr)
print(arr[0])

[0, 2, 3, 5]
0


In [3]:
# array usando numpy
# repare que usando o numpy o array printando tem algumas diferenças na separação dos elementos
arr2 = np.array([0, 2, 3, 5])
print(arr2)
print(arr2[0])


[0 2 3 5]
0


In [21]:
# a função arange gera uma PA de valor inicial como 1° arg, valor final com 2° arg, e o passo como 3° arg, além do tipo de informação que ele
# retorna, por exemplo, inteiros

arr = np.arange(0, 10, 1, int)
print(arr)

arr = np.arange(0, 50, 2, float)
print(arr)

arr = np.arange(0, 100, 1, int)
print(arr)



[0 1 2 3 4 5 6 7 8 9]
[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30. 32. 34.
 36. 38. 40. 42. 44. 46. 48.]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [22]:
# função reshape() serve para reestruturar um array sem alterar seu conteúdo

# faça um reshape para ordenar o array com 10 linhas e 10 colunas
arr = np.reshape(arr,(10,10))
print(arr)

print()

arr = np.reshape(arr,(5,20))
print(arr)

arr_mod = list()
arr_mod = np.reshape(arr, (20,5))
print(arr_mod)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97

In [25]:
# a indexação na biblioteca numpy é semelhante a indexação padrão do python, usando colchetes, a diferença é que aqui,
# para matrizes 2d (linha, coluna) nós passamos as coordenadas linha/coluna, veja:

print(arr_mod[2,3])
print(arr_mod[1,1])

13
6


In [27]:
# operação com matrizes, soma posição com posição

arr1 = np.array([ [2,3], [3,5] ])
arr2 = np.array([ [3,4], [9,8] ])

matriz_soma = arr1 + arr2
print(matriz_soma)

[[ 5  7]
 [12 13]]


In [28]:
#np.sum() soma todos os valores da matriz

arr = np.sum(matriz_soma)
print(arr)

37


In [31]:
# np.zeros() gera uma matriz de 3x3 com zeros, util para iniciar uma matriz

arr = np.zeros((3,3), int)
print(arr)

print()

arr = np.zeros(5, int)
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]

[0 0 0 0 0]


In [44]:
#np.random.rand(), função que gera numeros aleatório entre 0 e 1, e coloca tudo isso dentro de uma matriz

arr = np.random.rand(3,3)*100
print(arr)



[[66.25377969 23.60045713 27.08167213]
 [ 7.7972686  73.08347475 45.93535259]
 [53.0815813  68.72025994 42.40649412]]


In [49]:
# np.append() funciona exatamente igual o append() do python

arr = np.random.rand(5)*100
print(arr)

arr = np.append(arr, 35)
print(arr)

[79.57753692 58.03811443 78.79330506 31.66185561 72.15842466]
[79.57753692 58.03811443 78.79330506 31.66185561 72.15842466 35.        ]
